// Code generated by mockery v1.0.0. DO NOT EDIT.

package downloader

import mock "github.com/stretchr/testify/mock"
import tdlib "github.com/Arman92/go-tdlib"

// Mock is an autogenerated mock type for the Mock type
type Mock struct {
	mock.Mock
}

// DownloadChannelFile provides a mock function with given fields: src, dst
func (_m *Mock) DownloadChannelFile(src *tdlib.File, dst *string) error {
	ret := _m.Called(src, dst)

	var r0 error
	if rf, ok := ret.Get(0).(func(*tdlib.File, *string) error); ok {
		r0 = rf(src, dst)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WaitAllDownloads provides a mock function with given fields:
func (_m *Mock) WaitAllDownloads() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
