apiVersion: v1
kind: Secret
metadata:
  name: geochats
type: Opaque
data:
  tg_app_id: {{ .Values.app.tg.appId | b64enc | quote }}
  tg_app_hash: {{ .Values.app.tg.appHash | b64enc | quote }}
  tg_bot_token: {{ .Values.app.tg.botToken | b64enc | quote }}
  db_password: {{ .Values.app.db.pass | b64enc | quote }}